# Generated by Django 2.1.5 on 2019-03-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_auto_20190307_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='down_count',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='up_count',
        ),
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='踩数'),
        ),
        migrations.AddField(
            model_name='article',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
