# Generated by Django 2.2.1 on 2019-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190604_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatars/timg.jpg', upload_to='media/avatars/', verbose_name='头像'),
        ),
    ]
